dist: trusty

sudo: required

language: python

python:
  - 3.4
  - 3.5
  - 3.6

before_script:
  - pip3 install -e .

script:
  - python3 -c "import interact"
  = cd examples && python3 generate_interact_network.py
